### ISSUE TITLE
Installing skill through OSM: invalid MD5 URL

### ISSUE THREAD

**Issue by martini1992** [OpenVoiceOS/ovos-skill-naptime#12]
```
osm install https://github.com/OpenVoiceOS/skill-ovos-naptime
2023-04-08 04:57:40.369 - OVOS - ovos_utils.process_utils:PIDLock:301 - INFO - Create PIDLock in: None
2023-04-08 04:57:40.791 - OVOS - ovos_config.models:load_local:96 - DEBUG - Configuration /usr/local/lib/python3.9/dist-packages/mycroft/configuration/mycroft.conf loaded
2023-04-08 04:57:40.966 - OVOS - ovos_config.models:load_local:96 - DEBUG - Configuration /etc/mycroft/mycroft.conf loaded
2023-04-08 04:57:41.142 - OVOS - ovos_config.models:load_local:96 - DEBUG - Configuration /home/ovos/.config/mycroft/web_cache.json loaded
2023-04-08 04:57:41.320 - OVOS - ovos_config.models:load_local:98 - DEBUG - Empty config found at: /home/ovos/.config/mycroft/mycroft.conf
2023-04-08 04:57:41.545 - OVOS - ovos_config.models:load_local:102 - DEBUG - Configuration '/etc/xdg/mycroft/mycroft.conf' not defined, skipping
2023-04-08 04:57:41.706 - OVOS - ovos_config.models:load_local:102 - DEBUG - Configuration '/home/ovos/.mycroft/mycroft.conf' not defined, skipping
2023-04-08 04:57:52.355 - OVOS - ovos_skills_manager.github:get_requirements_json:209 - DEBUG - No manifest file available
2023-04-08 04:57:52.734 - OVOS - ovos_skills_manager.github:get_requirements_json:219 - DEBUG - No python requirements file available
2023-04-08 04:57:53.082 - OVOS - ovos_skills_manager.github:get_requirements_json:226 - DEBUG - No skill requirements file available

Search Results:
    appstore - branch - url 
1 - unknown - v0.2.2 https://github.com/OpenVoiceOS/skill-ovos-naptime
0 - cancel installation

Select an option: 1
Do you want to install v0.2.2 https://github.com/OpenVoiceOS/skill-ovos-naptime ? [y/N]: y
2023-04-08 04:58:03.954 - OVOS - ovos_utils.skills:get_skills_folder:90 - WARNING - This reference is deprecated, use `ovos_utils.skills.locations.get_default_skill_dir
2023-04-08 04:58:03.959 - OVOS - ovos_skills_manager.skill_entry:install:327 - INFO - Installing skill: https://github.com/OpenVoiceOS/skill-ovos-naptime from branch: v0.2.2
2023-04-08 04:58:03.961 - OVOS - ovos_skills_manager.skill_entry:install:347 - INFO - Downloading https://github.com/OpenVoiceOS/skill-ovos-naptime
Traceback (most recent call last):
  File "/home/ovos/.local/bin/osm", line 8, in <module>
    sys.exit(osm_commands())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ovos/.local/lib/python3.9/site-packages/ovos_skills_manager/commands.py", line 105, in install
    _install.install(method, skill, fuzzy, no_ignore_case, thresh, appstore, search,
  File "/home/ovos/.local/lib/python3.9/site-packages/ovos_skills_manager/scripts/install.py", line 96, in install
    skill.install(folder)
  File "/home/ovos/.local/lib/python3.9/site-packages/ovos_skills_manager/skill_entry.py", line 348, in install
    updated = self.download(folder)
  File "/home/ovos/.local/lib/python3.9/site-packages/ovos_skills_manager/skill_entry.py", line 302, in download
    return install_skill(url, folder, file, session=requests,
  File "/usr/local/lib/python3.9/dist-packages/ovos_skill_installer/__init__.py", line 177, in install_skill
    return install_skill_from_tar(url, folder, filename, md5_url,
  File "/usr/local/lib/python3.9/dist-packages/ovos_skill_installer/__init__.py", line 211, in install_skill_from_tar
    remote_md5, downloaded = get_remote_md5(md5_url, tar_url,
  File "/usr/local/lib/python3.9/dist-packages/ovos_skill_installer/__init__.py", line 150, in get_remote_md5
    raise ValueError('Invalid MD5 url: ' + md5_url)
ValueError: Invalid MD5 url: .md5

```

**Comment by JarbasAl** [comment]
OSM has been deprecated
